# Generated by Django 5.1.4 on 2025-02-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacion',
            name='fechaPlantacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
