# Generated by Django 5.1.4 on 2024-12-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_informe', models.CharField(max_length=100)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('datos_analizados', models.TextField()),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='plantaciones.plantacion')),
            ],
        ),
    ]
