# Generated by Django 5.1.4 on 2024-12-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cosechada', models.PositiveIntegerField()),
                ('calidad_media', models.TextField()),
                ('fecha_cosecha', models.DateField()),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='plantaciones.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='PostCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpieza_frutos', models.TextField()),
                ('cantidad_menos150', models.PositiveIntegerField()),
                ('cantidad_mayor250', models.PositiveIntegerField()),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_cosecha', to='plantaciones.plantacion')),
            ],
        ),
    ]
