# Generated by Django 5.1.4 on 2024-12-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis_suelo', models.TextField()),
                ('correccion_suelo', models.TextField()),
                ('labranza', models.TextField()),
                ('delimitacion_parcela', models.TextField()),
                ('fecha_preparacion', models.DateField()),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='plantaciones.plantacion')),
            ],
        ),
        migrations.CreateModel(
            name='SeleccionArboles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion_variedades', models.TextField()),
                ('preparacion_colinos', models.TextField()),
                ('plantacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seleccion_arboles', to='plantaciones.plantacion')),
            ],
        ),
    ]
